"""
Layer 5 — BI Output (Power BI Ready)
Exports final datasets optimized for direct import into Power BI.

Output files:
  fact_alerts.parquet         Main event-level fact table
  dim_rooms.parquet           Room dimension
  dim_event_types.parquet     Event type dimension with clinical metadata
  agg_room_day.parquet        Pre-aggregated room × day summary
  agg_hourly.parquet          Pre-aggregated hourly summary
  escalation_sequences.parquet Escalation patterns
  bursts.parquet              Alert burst patterns

  All Parquet files are also exported as .csv for easy Power BI import.

Power BI Import:
  1. Home → Get Data → CSV (or Parquet if pyarrow is available)
  2. Import fact_alerts.csv as the central fact table
  3. Import dim_rooms.csv and dim_event_types.csv as dimension tables
  4. Connect via room_id and event_type keys
  5. Use agg_* tables for pre-computed visuals (faster refresh)

Star Schema:
  fact_alerts ──► dim_rooms        (join: room_id)
              ──► dim_event_types  (join: event_type)
              ──► dim_date         (auto-generated by Power BI, join: date)
"""

import pandas as pd
import numpy as np
from pathlib import Path
from typing import Optional


def export_bi_datasets(
    events_df:      pd.DataFrame,
    escalation_df:  pd.DataFrame,
    bursts_df:      pd.DataFrame,
    output_dir:     str = "./data/bi_output",
) -> dict:
    """
    Main export function. Creates all Power BI-ready output tables.
    Returns a dict mapping {table_name: DataFrame}.
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    outputs = {}

    # 1. Central fact table
    fact = _build_fact_table(events_df)
    _save(fact, output_path / "fact_alerts.parquet", "fact_alerts.csv")
    outputs['fact_alerts'] = fact

    # 2. Dimension tables
    dim_rooms = _build_dim_rooms(events_df)
    _save(dim_rooms, output_path / "dim_rooms.parquet", "dim_rooms.csv")
    outputs['dim_rooms'] = dim_rooms

    dim_events = _build_dim_event_types(events_df)
    _save(dim_events, output_path / "dim_event_types.parquet", "dim_event_types.csv")
    outputs['dim_event_types'] = dim_events

    # 3. Pre-aggregated tables (faster Power BI visuals)
    agg_room_day = _build_agg_room_day(events_df)
    _save(agg_room_day, output_path / "agg_room_day.parquet", "agg_room_day.csv")
    outputs['agg_room_day'] = agg_room_day

    agg_hourly = _build_agg_hourly(events_df)
    _save(agg_hourly, output_path / "agg_hourly.parquet", "agg_hourly.csv")
    outputs['agg_hourly'] = agg_hourly

    # 4. Pattern analysis tables
    if not escalation_df.empty:
        _save(escalation_df, output_path / "escalation_sequences.parquet", "escalation_sequences.csv")
        outputs['escalation_sequences'] = escalation_df

    if not bursts_df.empty:
        _save(bursts_df, output_path / "bursts.parquet", "bursts.csv")
        outputs['bursts'] = bursts_df

    print(f"\n[Layer5] BI export complete → {output_path.resolve()}")
    for name, df in outputs.items():
        print(f"  {name}: {len(df):,} rows × {len(df.columns)} cols")

    return outputs


def _build_fact_table(events: pd.DataFrame) -> pd.DataFrame:
    """Build the central fact table with proper dtypes for Power BI."""
    fact = events[[
        'room_id', 'start_time', 'end_time', 'duration_sec',
        'severity', 'severity_label', 'event_type', 'action_type',
        'metric_value', 'threshold', 'condition',
        'alert_text', 'device_name', 'institution',
        'date', 'hour', 'weekday', 'is_noise',
    ]].copy()

    # Enforce correct types
    fact['duration_sec']  = pd.to_numeric(fact['duration_sec'],  errors='coerce').round(1)
    fact['metric_value']  = pd.to_numeric(fact['metric_value'],  errors='coerce').round(1)
    fact['threshold']     = pd.to_numeric(fact['threshold'],     errors='coerce').round(1)
    fact['severity']      = fact['severity'].astype('Int8')
    fact['hour']          = fact['hour'].astype('Int8')
    fact['is_noise']      = fact['is_noise'].astype(bool)
    fact['date']          = pd.to_datetime(fact['date'])

    # Derived columns for Power BI measures
    fact['duration_min']          = (fact['duration_sec'] / 60).round(2)
    fact['noise_flag']            = fact['is_noise'].map({True: 'Noise', False: 'Signal'})
    fact['severity_text']         = fact['severity'].map({1: 'Low (★)', 2: 'Medium (★★)', 3: 'Critical (★★★)'})
    fact['delta_from_threshold']  = (fact['metric_value'] - fact['threshold']).round(1)

    return fact.sort_values('start_time').reset_index(drop=True)


def _build_dim_rooms(events: pd.DataFrame) -> pd.DataFrame:
    """Room dimension table with aggregate statistics."""
    dim = events.groupby('room_id').agg(
        institution    = ('institution', 'first'),
        device_name    = ('device_name', 'first'),
        total_alerts   = ('event_type', 'count'),
        critical_alerts = ('severity', lambda x: (x == 3).sum()),
        noise_alerts   = ('is_noise', 'sum'),
        first_seen     = ('start_time', 'min'),
        last_seen      = ('start_time', 'max'),
    ).reset_index()
    dim['noise_pct'] = (dim['noise_alerts'] / dim['total_alerts'] * 100).round(1)
    return dim


def _build_dim_event_types(events: pd.DataFrame) -> pd.DataFrame:
    """Event type dimension with clinical category and risk level metadata."""
    dim = events.groupby('event_type').agg(
        count            = ('event_type', 'count'),
        avg_severity     = ('severity', 'mean'),
        avg_duration_sec = ('duration_sec', 'mean'),
        noise_pct        = ('is_noise', lambda x: round(x.mean() * 100, 1)),
    ).reset_index().round(2)

    # Clinical category mapping
    category_map = {
        'HR':          'Cardiac',   'Brady':         'Cardiac',
        'VTach':       'Cardiac',   'VFib':          'Cardiac',
        'NonSustainVT':'Cardiac',   'IrregularHR':   'Cardiac',
        'RunPVCs':     'Cardiac',   'Asystole':      'Cardiac',
        'SpO2':        'Respiratory', 'Desat':        'Respiratory',
        'RR':          'Respiratory', 'Apnea':        'Respiratory',
        'NBPs':        'Hemodynamic', 'NBPd':         'Hemodynamic',
        'TEMP':        'Metabolic',
    }
    dim['clinical_category'] = dim['event_type'].map(category_map).fillna('Other')

    # Clinical risk level
    high_risk   = {'VTach', 'VFib', 'Asystole', 'Desat', 'Apnea'}
    medium_risk = {'Brady', 'IrregularHR', 'NonSustainVT'}
    dim['risk_level'] = dim['event_type'].apply(
        lambda x: 'High' if x in high_risk else ('Medium' if x in medium_risk else 'Low')
    )

    return dim.sort_values('count', ascending=False)


def _build_agg_room_day(events: pd.DataFrame) -> pd.DataFrame:
    """Pre-aggregated room × day table for Power BI dashboard visuals."""
    agg = events.groupby(['room_id', 'date']).agg(
        total_alerts        = ('event_type', 'count'),
        critical_alerts     = ('severity', lambda x: (x == 3).sum()),
        noise_alerts        = ('is_noise', 'sum'),
        unique_event_types  = ('event_type', 'nunique'),
        avg_duration_sec    = ('duration_sec', 'mean'),
        max_severity        = ('severity', 'max'),
    ).reset_index()
    agg['date']             = pd.to_datetime(agg['date'])
    agg['noise_pct']        = (agg['noise_alerts'] / agg['total_alerts'] * 100).round(1)
    agg['avg_duration_sec'] = agg['avg_duration_sec'].round(1)
    return agg


def _build_agg_hourly(events: pd.DataFrame) -> pd.DataFrame:
    """Pre-aggregated hourly breakdown for Power BI time-of-day analysis."""
    agg = events.groupby(['date', 'hour']).agg(
        total_alerts    = ('event_type', 'count'),
        critical_alerts = ('severity', lambda x: (x == 3).sum()),
        noise_alerts    = ('is_noise', 'sum'),
        unique_rooms    = ('room_id', 'nunique'),
    ).reset_index()
    agg['date']       = pd.to_datetime(agg['date'])
    agg['hour_label'] = agg['hour'].apply(lambda h: f"{h:02d}:00")
    return agg


def _save(df: pd.DataFrame, parquet_path: Path, csv_filename: str):
    """Save as both Parquet (primary) and CSV (fallback for Power BI import)."""
    try:
        df.to_parquet(parquet_path, index=False)
    except Exception:
        pass  # pyarrow may not be available; CSV is always produced
    df.to_csv(parquet_path.parent / csv_filename, index=False)
